import os
from pathlib import Path

from crewai import Agent, LLM
from dotenv import load_dotenv

load_dotenv(Path(__file__).resolve().parents[1] / ".env")

llm = LLM(
    model="gemini/gemini-2.5-flash",
    api_key=os.getenv("GOOGLE_API_KEY"),
    temperature=0.2
)


def get_agents():

    planner = Agent(
        role="Business Analyst",
        goal="""
        Read the entire SRS document thoroughly, covering EVERY page, EVERY section,
        EVERY line, EVERY word, EVERY table, and EVERY field without skipping anything.

        Extract ALL possible functional and non-functional requirements.
        Capture validations, workflows, dependencies, conditions, edge rules, API behavior,
        field-level constraints, and business logic.

        Ensure NOTHING is missed. The output must be complete, structured, and exhaustive.
        """,
        backstory="Highly experienced Business Analyst who never misses any detail",
        llm=llm,
        verbose=True
    )

    generator = Agent(
        role="QA Engineer",
        goal="""
        Analyze ALL extracted requirements deeply and generate EVERY possible test case.

        Cover:
        - Functional test cases
        - Validation test cases
        - Negative test cases
        - Edge cases
        - Boundary cases
        - UI/field validation cases
        - API test cases
        - Integration test cases
        - End-to-end workflow cases
        - Role-based scenarios
        - Security and data validation cases

        Ensure industry-level coverage with NO missing scenarios.
        Test cases should be detailed, realistic, and exhaustive.
        """,
        backstory="Senior QA engineer with expertise in enterprise-level testing",
        llm=llm,
        verbose=True
    )

    critic = Agent(
        role="QA Reviewer",
        goal="""
        Critically review EVERYTHING generated by the Business Analyst and QA Engineer.

        Identify:
        - Missing scenarios
        - Weak test cases
        - Gaps in coverage
        - Incorrect assumptions

        Improve and enhance test cases to:
        - Industry standards
        - Maximum coverage
        - Better clarity and structure

        Add any missing edge cases, negative cases, and complex scenarios.
        Ensure ZERO gaps remain.
        """,
        backstory="Expert QA reviewer ensuring enterprise-grade quality",
        llm=llm,
        verbose=True
    )

    refiner = Agent(
        role="Finalizer",
        goal="""
        Review all outputs from previous agents and finalize the BEST possible set of test cases.

        Ensure:
        - Clean structure
        - No duplicates
        - No irrelevant cases
        - Maximum meaningful coverage

        Return ONLY final test cases in STRICT JSON format:
        [
          {
            Test case No.: "...",
            Function List/Test case description: "...",
            Condition/Feature to be tested: "...",
            "steps": "...",
            data set / values: "...",
            "expected_result": "..."
          }
        ]

        No explanations. No extra text. ONLY JSON.
        """,
        backstory="Automation QA expert delivering final production-ready output",
        llm=llm,
        verbose=True
    )

    return planner, generator, critic, refiner
